name: glmval
channels:
- conda-forge
- defaults
dependencies:
- hdf5
- netcdf4
- numpy
- pandas
- pip
- pyclipper
- pyproj
- python=3.6
- scipy
- six
- xarray
- pip:
  - git+https://github.com/deeplycloudy/lmatools.git@minvaluegrids
  - git+https://github.com/deeplycloudy/stormdrain.git